/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOutreachIndexRouteImport } from './routes/_app.outreach.index'
import { Route as AppOutreachUsersRouteImport } from './routes/_app.outreach.users'
import { Route as AppOutreachUnlockedRouteImport } from './routes/_app.outreach.unlocked'
import { Route as AppOutreachSuppressionsRouteImport } from './routes/_app.outreach.suppressions'
import { Route as AppOutreachSearchRouteImport } from './routes/_app.outreach.search'
import { Route as AppOutreachRechargeRouteImport } from './routes/_app.outreach.recharge'
import { Route as AppOutreachReachEmptyRouteImport } from './routes/_app.outreach.reach-empty'
import { Route as AppOutreachReachRouteImport } from './routes/_app.outreach.reach'
import { Route as AppOutreachMyProfileRouteImport } from './routes/_app.outreach.my-profile'
import { Route as AppOutreachMailboxesRouteImport } from './routes/_app.outreach.mailboxes'
import { Route as AppOutreachLeadsRouteImport } from './routes/_app.outreach.leads'
import { Route as AppOutreachInvoicesRouteImport } from './routes/_app.outreach.invoices'
import { Route as AppOutreachInquiryDispatchRouteImport } from './routes/_app.outreach.inquiry-dispatch'
import { Route as AppOutreachFootprintsEmptyRouteImport } from './routes/_app.outreach.footprints-empty'
import { Route as AppOutreachFootprintsRouteImport } from './routes/_app.outreach.footprints'
import { Route as AppOutreachFavoritesEmptyRouteImport } from './routes/_app.outreach.favorites-empty'
import { Route as AppOutreachFavoritesRouteImport } from './routes/_app.outreach.favorites'
import { Route as AppOutreachEnterpriseRouteImport } from './routes/_app.outreach.enterprise'
import { Route as AppOutreachConversationsRouteImport } from './routes/_app.outreach.conversations'
import { Route as AppOutreachBillsRouteImport } from './routes/_app.outreach.bills'
import { Route as AppOutreachBillingEmptyRouteImport } from './routes/_app.outreach.billing-empty'
import { Route as AppOutreachBillingRouteImport } from './routes/_app.outreach.billing'
import { Route as AppOutreachProductsIndexRouteImport } from './routes/_app.outreach.products.index'
import { Route as AppOutreachEnterpriseIndexRouteImport } from './routes/_app.outreach.enterprise.index'
import { Route as AppOutreachSocialReachRouteImport } from './routes/_app.outreach.social.reach'
import { Route as AppOutreachSocialFriendsRouteImport } from './routes/_app.outreach.social.friends'
import { Route as AppOutreachSocialDmRouteImport } from './routes/_app.outreach.social.dm'
import { Route as AppOutreachSocialAccountsRouteImport } from './routes/_app.outreach.social.accounts'
import { Route as AppOutreachProductsHsRouteImport } from './routes/_app.outreach.products.$hs'
import { Route as AppOutreachEnterpriseIdRouteImport } from './routes/_app.outreach.enterprise.$id'
import { Route as AppOutreachAdminSmsTemplatesRouteImport } from './routes/_app.outreach.admin.sms-templates'
import { Route as AppOutreachAdminSmsRoutingRouteImport } from './routes/_app.outreach.admin.sms-routing'
import { Route as AppOutreachAdminSmsProvidersRouteImport } from './routes/_app.outreach.admin.sms-providers'
import { Route as AppOutreachAdminInvoiceReviewRouteImport } from './routes/_app.outreach.admin.invoice-review'
import { Route as AppOutreachAdminEmailProvidersRouteImport } from './routes/_app.outreach.admin.email-providers'
import { Route as AppOutreachAdminEmailAccountsRouteImport } from './routes/_app.outreach.admin.email-accounts'
import { Route as AppOutreachSocialReachIndexRouteImport } from './routes/_app.outreach.social.reach.index'
import { Route as AppOutreachSocialProspectingIndexRouteImport } from './routes/_app.outreach.social.prospecting.index'
import { Route as AppOutreachEnterpriseIdIndexRouteImport } from './routes/_app.outreach.enterprise.$id.index'
import { Route as AppOutreachSocialReachDmRouteImport } from './routes/_app.outreach.social.reach.dm'
import { Route as AppOutreachSocialProspectingTaskIdRouteImport } from './routes/_app.outreach.social.prospecting.$taskId'
import { Route as AppOutreachSocialReachProspectingIndexRouteImport } from './routes/_app.outreach.social.reach.prospecting.index'
import { Route as AppOutreachSocialReachProspectingTaskIdRouteImport } from './routes/_app.outreach.social.reach.prospecting.$taskId'
import { Route as AppOutreachEnterpriseIdContactIdxRouteImport } from './routes/_app.outreach.enterprise.$id.contact.$idx'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachIndexRoute = AppOutreachIndexRouteImport.update({
  id: '/outreach/',
  path: '/outreach/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachUsersRoute = AppOutreachUsersRouteImport.update({
  id: '/outreach/users',
  path: '/outreach/users',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachUnlockedRoute = AppOutreachUnlockedRouteImport.update({
  id: '/outreach/unlocked',
  path: '/outreach/unlocked',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachSuppressionsRoute = AppOutreachSuppressionsRouteImport.update({
  id: '/outreach/suppressions',
  path: '/outreach/suppressions',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachSearchRoute = AppOutreachSearchRouteImport.update({
  id: '/outreach/search',
  path: '/outreach/search',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRechargeRoute = AppOutreachRechargeRouteImport.update({
  id: '/outreach/recharge',
  path: '/outreach/recharge',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachReachEmptyRoute = AppOutreachReachEmptyRouteImport.update({
  id: '/outreach/reach-empty',
  path: '/outreach/reach-empty',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachReachRoute = AppOutreachReachRouteImport.update({
  id: '/outreach/reach',
  path: '/outreach/reach',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachMyProfileRoute = AppOutreachMyProfileRouteImport.update({
  id: '/outreach/my-profile',
  path: '/outreach/my-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachMailboxesRoute = AppOutreachMailboxesRouteImport.update({
  id: '/outreach/mailboxes',
  path: '/outreach/mailboxes',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachLeadsRoute = AppOutreachLeadsRouteImport.update({
  id: '/outreach/leads',
  path: '/outreach/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachInvoicesRoute = AppOutreachInvoicesRouteImport.update({
  id: '/outreach/invoices',
  path: '/outreach/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachInquiryDispatchRoute =
  AppOutreachInquiryDispatchRouteImport.update({
    id: '/outreach/inquiry-dispatch',
    path: '/outreach/inquiry-dispatch',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachFootprintsEmptyRoute =
  AppOutreachFootprintsEmptyRouteImport.update({
    id: '/outreach/footprints-empty',
    path: '/outreach/footprints-empty',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachFootprintsRoute = AppOutreachFootprintsRouteImport.update({
  id: '/outreach/footprints',
  path: '/outreach/footprints',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachFavoritesEmptyRoute =
  AppOutreachFavoritesEmptyRouteImport.update({
    id: '/outreach/favorites-empty',
    path: '/outreach/favorites-empty',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachFavoritesRoute = AppOutreachFavoritesRouteImport.update({
  id: '/outreach/favorites',
  path: '/outreach/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachEnterpriseRoute = AppOutreachEnterpriseRouteImport.update({
  id: '/outreach/enterprise',
  path: '/outreach/enterprise',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachConversationsRoute =
  AppOutreachConversationsRouteImport.update({
    id: '/outreach/conversations',
    path: '/outreach/conversations',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachBillsRoute = AppOutreachBillsRouteImport.update({
  id: '/outreach/bills',
  path: '/outreach/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachBillingEmptyRoute = AppOutreachBillingEmptyRouteImport.update({
  id: '/outreach/billing-empty',
  path: '/outreach/billing-empty',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachBillingRoute = AppOutreachBillingRouteImport.update({
  id: '/outreach/billing',
  path: '/outreach/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachProductsIndexRoute =
  AppOutreachProductsIndexRouteImport.update({
    id: '/outreach/products/',
    path: '/outreach/products/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachEnterpriseIndexRoute =
  AppOutreachEnterpriseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOutreachEnterpriseRoute,
  } as any)
const AppOutreachSocialReachRoute = AppOutreachSocialReachRouteImport.update({
  id: '/outreach/social/reach',
  path: '/outreach/social/reach',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachSocialFriendsRoute =
  AppOutreachSocialFriendsRouteImport.update({
    id: '/outreach/social/friends',
    path: '/outreach/social/friends',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachSocialDmRoute = AppOutreachSocialDmRouteImport.update({
  id: '/outreach/social/dm',
  path: '/outreach/social/dm',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachSocialAccountsRoute =
  AppOutreachSocialAccountsRouteImport.update({
    id: '/outreach/social/accounts',
    path: '/outreach/social/accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachProductsHsRoute = AppOutreachProductsHsRouteImport.update({
  id: '/outreach/products/$hs',
  path: '/outreach/products/$hs',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachEnterpriseIdRoute = AppOutreachEnterpriseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOutreachEnterpriseRoute,
} as any)
const AppOutreachAdminSmsTemplatesRoute =
  AppOutreachAdminSmsTemplatesRouteImport.update({
    id: '/outreach/admin/sms-templates',
    path: '/outreach/admin/sms-templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachAdminSmsRoutingRoute =
  AppOutreachAdminSmsRoutingRouteImport.update({
    id: '/outreach/admin/sms-routing',
    path: '/outreach/admin/sms-routing',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachAdminSmsProvidersRoute =
  AppOutreachAdminSmsProvidersRouteImport.update({
    id: '/outreach/admin/sms-providers',
    path: '/outreach/admin/sms-providers',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachAdminInvoiceReviewRoute =
  AppOutreachAdminInvoiceReviewRouteImport.update({
    id: '/outreach/admin/invoice-review',
    path: '/outreach/admin/invoice-review',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachAdminEmailProvidersRoute =
  AppOutreachAdminEmailProvidersRouteImport.update({
    id: '/outreach/admin/email-providers',
    path: '/outreach/admin/email-providers',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachAdminEmailAccountsRoute =
  AppOutreachAdminEmailAccountsRouteImport.update({
    id: '/outreach/admin/email-accounts',
    path: '/outreach/admin/email-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachSocialReachIndexRoute =
  AppOutreachSocialReachIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOutreachSocialReachRoute,
  } as any)
const AppOutreachSocialProspectingIndexRoute =
  AppOutreachSocialProspectingIndexRouteImport.update({
    id: '/outreach/social/prospecting/',
    path: '/outreach/social/prospecting/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachEnterpriseIdIndexRoute =
  AppOutreachEnterpriseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOutreachEnterpriseIdRoute,
  } as any)
const AppOutreachSocialReachDmRoute =
  AppOutreachSocialReachDmRouteImport.update({
    id: '/dm',
    path: '/dm',
    getParentRoute: () => AppOutreachSocialReachRoute,
  } as any)
const AppOutreachSocialProspectingTaskIdRoute =
  AppOutreachSocialProspectingTaskIdRouteImport.update({
    id: '/outreach/social/prospecting/$taskId',
    path: '/outreach/social/prospecting/$taskId',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachSocialReachProspectingIndexRoute =
  AppOutreachSocialReachProspectingIndexRouteImport.update({
    id: '/prospecting/',
    path: '/prospecting/',
    getParentRoute: () => AppOutreachSocialReachRoute,
  } as any)
const AppOutreachSocialReachProspectingTaskIdRoute =
  AppOutreachSocialReachProspectingTaskIdRouteImport.update({
    id: '/prospecting/$taskId',
    path: '/prospecting/$taskId',
    getParentRoute: () => AppOutreachSocialReachRoute,
  } as any)
const AppOutreachEnterpriseIdContactIdxRoute =
  AppOutreachEnterpriseIdContactIdxRouteImport.update({
    id: '/contact/$idx',
    path: '/contact/$idx',
    getParentRoute: () => AppOutreachEnterpriseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/outreach/billing': typeof AppOutreachBillingRoute
  '/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/outreach/bills': typeof AppOutreachBillsRoute
  '/outreach/conversations': typeof AppOutreachConversationsRoute
  '/outreach/enterprise': typeof AppOutreachEnterpriseRouteWithChildren
  '/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/outreach/inquiry-dispatch': typeof AppOutreachInquiryDispatchRoute
  '/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/outreach/leads': typeof AppOutreachLeadsRoute
  '/outreach/mailboxes': typeof AppOutreachMailboxesRoute
  '/outreach/my-profile': typeof AppOutreachMyProfileRoute
  '/outreach/reach': typeof AppOutreachReachRoute
  '/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/outreach/recharge': typeof AppOutreachRechargeRoute
  '/outreach/search': typeof AppOutreachSearchRoute
  '/outreach/suppressions': typeof AppOutreachSuppressionsRoute
  '/outreach/unlocked': typeof AppOutreachUnlockedRoute
  '/outreach/users': typeof AppOutreachUsersRoute
  '/outreach/': typeof AppOutreachIndexRoute
  '/outreach/admin/email-accounts': typeof AppOutreachAdminEmailAccountsRoute
  '/outreach/admin/email-providers': typeof AppOutreachAdminEmailProvidersRoute
  '/outreach/admin/invoice-review': typeof AppOutreachAdminInvoiceReviewRoute
  '/outreach/admin/sms-providers': typeof AppOutreachAdminSmsProvidersRoute
  '/outreach/admin/sms-routing': typeof AppOutreachAdminSmsRoutingRoute
  '/outreach/admin/sms-templates': typeof AppOutreachAdminSmsTemplatesRoute
  '/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdRouteWithChildren
  '/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/outreach/social/accounts': typeof AppOutreachSocialAccountsRoute
  '/outreach/social/dm': typeof AppOutreachSocialDmRoute
  '/outreach/social/friends': typeof AppOutreachSocialFriendsRoute
  '/outreach/social/reach': typeof AppOutreachSocialReachRouteWithChildren
  '/outreach/enterprise/': typeof AppOutreachEnterpriseIndexRoute
  '/outreach/products/': typeof AppOutreachProductsIndexRoute
  '/outreach/social/prospecting/$taskId': typeof AppOutreachSocialProspectingTaskIdRoute
  '/outreach/social/reach/dm': typeof AppOutreachSocialReachDmRoute
  '/outreach/enterprise/$id/': typeof AppOutreachEnterpriseIdIndexRoute
  '/outreach/social/prospecting/': typeof AppOutreachSocialProspectingIndexRoute
  '/outreach/social/reach/': typeof AppOutreachSocialReachIndexRoute
  '/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
  '/outreach/social/reach/prospecting/$taskId': typeof AppOutreachSocialReachProspectingTaskIdRoute
  '/outreach/social/reach/prospecting/': typeof AppOutreachSocialReachProspectingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/outreach/billing': typeof AppOutreachBillingRoute
  '/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/outreach/bills': typeof AppOutreachBillsRoute
  '/outreach/conversations': typeof AppOutreachConversationsRoute
  '/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/outreach/inquiry-dispatch': typeof AppOutreachInquiryDispatchRoute
  '/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/outreach/leads': typeof AppOutreachLeadsRoute
  '/outreach/mailboxes': typeof AppOutreachMailboxesRoute
  '/outreach/my-profile': typeof AppOutreachMyProfileRoute
  '/outreach/reach': typeof AppOutreachReachRoute
  '/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/outreach/recharge': typeof AppOutreachRechargeRoute
  '/outreach/search': typeof AppOutreachSearchRoute
  '/outreach/suppressions': typeof AppOutreachSuppressionsRoute
  '/outreach/unlocked': typeof AppOutreachUnlockedRoute
  '/outreach/users': typeof AppOutreachUsersRoute
  '/outreach': typeof AppOutreachIndexRoute
  '/outreach/admin/email-accounts': typeof AppOutreachAdminEmailAccountsRoute
  '/outreach/admin/email-providers': typeof AppOutreachAdminEmailProvidersRoute
  '/outreach/admin/invoice-review': typeof AppOutreachAdminInvoiceReviewRoute
  '/outreach/admin/sms-providers': typeof AppOutreachAdminSmsProvidersRoute
  '/outreach/admin/sms-routing': typeof AppOutreachAdminSmsRoutingRoute
  '/outreach/admin/sms-templates': typeof AppOutreachAdminSmsTemplatesRoute
  '/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/outreach/social/accounts': typeof AppOutreachSocialAccountsRoute
  '/outreach/social/dm': typeof AppOutreachSocialDmRoute
  '/outreach/social/friends': typeof AppOutreachSocialFriendsRoute
  '/outreach/enterprise': typeof AppOutreachEnterpriseIndexRoute
  '/outreach/products': typeof AppOutreachProductsIndexRoute
  '/outreach/social/prospecting/$taskId': typeof AppOutreachSocialProspectingTaskIdRoute
  '/outreach/social/reach/dm': typeof AppOutreachSocialReachDmRoute
  '/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdIndexRoute
  '/outreach/social/prospecting': typeof AppOutreachSocialProspectingIndexRoute
  '/outreach/social/reach': typeof AppOutreachSocialReachIndexRoute
  '/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
  '/outreach/social/reach/prospecting/$taskId': typeof AppOutreachSocialReachProspectingTaskIdRoute
  '/outreach/social/reach/prospecting': typeof AppOutreachSocialReachProspectingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/outreach/billing': typeof AppOutreachBillingRoute
  '/_app/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/_app/outreach/bills': typeof AppOutreachBillsRoute
  '/_app/outreach/conversations': typeof AppOutreachConversationsRoute
  '/_app/outreach/enterprise': typeof AppOutreachEnterpriseRouteWithChildren
  '/_app/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/_app/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/_app/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/_app/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/_app/outreach/inquiry-dispatch': typeof AppOutreachInquiryDispatchRoute
  '/_app/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/_app/outreach/leads': typeof AppOutreachLeadsRoute
  '/_app/outreach/mailboxes': typeof AppOutreachMailboxesRoute
  '/_app/outreach/my-profile': typeof AppOutreachMyProfileRoute
  '/_app/outreach/reach': typeof AppOutreachReachRoute
  '/_app/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/_app/outreach/recharge': typeof AppOutreachRechargeRoute
  '/_app/outreach/search': typeof AppOutreachSearchRoute
  '/_app/outreach/suppressions': typeof AppOutreachSuppressionsRoute
  '/_app/outreach/unlocked': typeof AppOutreachUnlockedRoute
  '/_app/outreach/users': typeof AppOutreachUsersRoute
  '/_app/outreach/': typeof AppOutreachIndexRoute
  '/_app/outreach/admin/email-accounts': typeof AppOutreachAdminEmailAccountsRoute
  '/_app/outreach/admin/email-providers': typeof AppOutreachAdminEmailProvidersRoute
  '/_app/outreach/admin/invoice-review': typeof AppOutreachAdminInvoiceReviewRoute
  '/_app/outreach/admin/sms-providers': typeof AppOutreachAdminSmsProvidersRoute
  '/_app/outreach/admin/sms-routing': typeof AppOutreachAdminSmsRoutingRoute
  '/_app/outreach/admin/sms-templates': typeof AppOutreachAdminSmsTemplatesRoute
  '/_app/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdRouteWithChildren
  '/_app/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/_app/outreach/social/accounts': typeof AppOutreachSocialAccountsRoute
  '/_app/outreach/social/dm': typeof AppOutreachSocialDmRoute
  '/_app/outreach/social/friends': typeof AppOutreachSocialFriendsRoute
  '/_app/outreach/social/reach': typeof AppOutreachSocialReachRouteWithChildren
  '/_app/outreach/enterprise/': typeof AppOutreachEnterpriseIndexRoute
  '/_app/outreach/products/': typeof AppOutreachProductsIndexRoute
  '/_app/outreach/social/prospecting/$taskId': typeof AppOutreachSocialProspectingTaskIdRoute
  '/_app/outreach/social/reach/dm': typeof AppOutreachSocialReachDmRoute
  '/_app/outreach/enterprise/$id/': typeof AppOutreachEnterpriseIdIndexRoute
  '/_app/outreach/social/prospecting/': typeof AppOutreachSocialProspectingIndexRoute
  '/_app/outreach/social/reach/': typeof AppOutreachSocialReachIndexRoute
  '/_app/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
  '/_app/outreach/social/reach/prospecting/$taskId': typeof AppOutreachSocialReachProspectingTaskIdRoute
  '/_app/outreach/social/reach/prospecting/': typeof AppOutreachSocialReachProspectingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/outreach/billing'
    | '/outreach/billing-empty'
    | '/outreach/bills'
    | '/outreach/conversations'
    | '/outreach/enterprise'
    | '/outreach/favorites'
    | '/outreach/favorites-empty'
    | '/outreach/footprints'
    | '/outreach/footprints-empty'
    | '/outreach/inquiry-dispatch'
    | '/outreach/invoices'
    | '/outreach/leads'
    | '/outreach/mailboxes'
    | '/outreach/my-profile'
    | '/outreach/reach'
    | '/outreach/reach-empty'
    | '/outreach/recharge'
    | '/outreach/search'
    | '/outreach/suppressions'
    | '/outreach/unlocked'
    | '/outreach/users'
    | '/outreach/'
    | '/outreach/admin/email-accounts'
    | '/outreach/admin/email-providers'
    | '/outreach/admin/invoice-review'
    | '/outreach/admin/sms-providers'
    | '/outreach/admin/sms-routing'
    | '/outreach/admin/sms-templates'
    | '/outreach/enterprise/$id'
    | '/outreach/products/$hs'
    | '/outreach/social/accounts'
    | '/outreach/social/dm'
    | '/outreach/social/friends'
    | '/outreach/social/reach'
    | '/outreach/enterprise/'
    | '/outreach/products/'
    | '/outreach/social/prospecting/$taskId'
    | '/outreach/social/reach/dm'
    | '/outreach/enterprise/$id/'
    | '/outreach/social/prospecting/'
    | '/outreach/social/reach/'
    | '/outreach/enterprise/$id/contact/$idx'
    | '/outreach/social/reach/prospecting/$taskId'
    | '/outreach/social/reach/prospecting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/outreach/billing'
    | '/outreach/billing-empty'
    | '/outreach/bills'
    | '/outreach/conversations'
    | '/outreach/favorites'
    | '/outreach/favorites-empty'
    | '/outreach/footprints'
    | '/outreach/footprints-empty'
    | '/outreach/inquiry-dispatch'
    | '/outreach/invoices'
    | '/outreach/leads'
    | '/outreach/mailboxes'
    | '/outreach/my-profile'
    | '/outreach/reach'
    | '/outreach/reach-empty'
    | '/outreach/recharge'
    | '/outreach/search'
    | '/outreach/suppressions'
    | '/outreach/unlocked'
    | '/outreach/users'
    | '/outreach'
    | '/outreach/admin/email-accounts'
    | '/outreach/admin/email-providers'
    | '/outreach/admin/invoice-review'
    | '/outreach/admin/sms-providers'
    | '/outreach/admin/sms-routing'
    | '/outreach/admin/sms-templates'
    | '/outreach/products/$hs'
    | '/outreach/social/accounts'
    | '/outreach/social/dm'
    | '/outreach/social/friends'
    | '/outreach/enterprise'
    | '/outreach/products'
    | '/outreach/social/prospecting/$taskId'
    | '/outreach/social/reach/dm'
    | '/outreach/enterprise/$id'
    | '/outreach/social/prospecting'
    | '/outreach/social/reach'
    | '/outreach/enterprise/$id/contact/$idx'
    | '/outreach/social/reach/prospecting/$taskId'
    | '/outreach/social/reach/prospecting'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/outreach/billing'
    | '/_app/outreach/billing-empty'
    | '/_app/outreach/bills'
    | '/_app/outreach/conversations'
    | '/_app/outreach/enterprise'
    | '/_app/outreach/favorites'
    | '/_app/outreach/favorites-empty'
    | '/_app/outreach/footprints'
    | '/_app/outreach/footprints-empty'
    | '/_app/outreach/inquiry-dispatch'
    | '/_app/outreach/invoices'
    | '/_app/outreach/leads'
    | '/_app/outreach/mailboxes'
    | '/_app/outreach/my-profile'
    | '/_app/outreach/reach'
    | '/_app/outreach/reach-empty'
    | '/_app/outreach/recharge'
    | '/_app/outreach/search'
    | '/_app/outreach/suppressions'
    | '/_app/outreach/unlocked'
    | '/_app/outreach/users'
    | '/_app/outreach/'
    | '/_app/outreach/admin/email-accounts'
    | '/_app/outreach/admin/email-providers'
    | '/_app/outreach/admin/invoice-review'
    | '/_app/outreach/admin/sms-providers'
    | '/_app/outreach/admin/sms-routing'
    | '/_app/outreach/admin/sms-templates'
    | '/_app/outreach/enterprise/$id'
    | '/_app/outreach/products/$hs'
    | '/_app/outreach/social/accounts'
    | '/_app/outreach/social/dm'
    | '/_app/outreach/social/friends'
    | '/_app/outreach/social/reach'
    | '/_app/outreach/enterprise/'
    | '/_app/outreach/products/'
    | '/_app/outreach/social/prospecting/$taskId'
    | '/_app/outreach/social/reach/dm'
    | '/_app/outreach/enterprise/$id/'
    | '/_app/outreach/social/prospecting/'
    | '/_app/outreach/social/reach/'
    | '/_app/outreach/enterprise/$id/contact/$idx'
    | '/_app/outreach/social/reach/prospecting/$taskId'
    | '/_app/outreach/social/reach/prospecting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/': {
      id: '/_app/outreach/'
      path: '/outreach'
      fullPath: '/outreach/'
      preLoaderRoute: typeof AppOutreachIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/users': {
      id: '/_app/outreach/users'
      path: '/outreach/users'
      fullPath: '/outreach/users'
      preLoaderRoute: typeof AppOutreachUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/unlocked': {
      id: '/_app/outreach/unlocked'
      path: '/outreach/unlocked'
      fullPath: '/outreach/unlocked'
      preLoaderRoute: typeof AppOutreachUnlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/suppressions': {
      id: '/_app/outreach/suppressions'
      path: '/outreach/suppressions'
      fullPath: '/outreach/suppressions'
      preLoaderRoute: typeof AppOutreachSuppressionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/search': {
      id: '/_app/outreach/search'
      path: '/outreach/search'
      fullPath: '/outreach/search'
      preLoaderRoute: typeof AppOutreachSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/recharge': {
      id: '/_app/outreach/recharge'
      path: '/outreach/recharge'
      fullPath: '/outreach/recharge'
      preLoaderRoute: typeof AppOutreachRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/reach-empty': {
      id: '/_app/outreach/reach-empty'
      path: '/outreach/reach-empty'
      fullPath: '/outreach/reach-empty'
      preLoaderRoute: typeof AppOutreachReachEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/reach': {
      id: '/_app/outreach/reach'
      path: '/outreach/reach'
      fullPath: '/outreach/reach'
      preLoaderRoute: typeof AppOutreachReachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/my-profile': {
      id: '/_app/outreach/my-profile'
      path: '/outreach/my-profile'
      fullPath: '/outreach/my-profile'
      preLoaderRoute: typeof AppOutreachMyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/mailboxes': {
      id: '/_app/outreach/mailboxes'
      path: '/outreach/mailboxes'
      fullPath: '/outreach/mailboxes'
      preLoaderRoute: typeof AppOutreachMailboxesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/leads': {
      id: '/_app/outreach/leads'
      path: '/outreach/leads'
      fullPath: '/outreach/leads'
      preLoaderRoute: typeof AppOutreachLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/invoices': {
      id: '/_app/outreach/invoices'
      path: '/outreach/invoices'
      fullPath: '/outreach/invoices'
      preLoaderRoute: typeof AppOutreachInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/inquiry-dispatch': {
      id: '/_app/outreach/inquiry-dispatch'
      path: '/outreach/inquiry-dispatch'
      fullPath: '/outreach/inquiry-dispatch'
      preLoaderRoute: typeof AppOutreachInquiryDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/footprints-empty': {
      id: '/_app/outreach/footprints-empty'
      path: '/outreach/footprints-empty'
      fullPath: '/outreach/footprints-empty'
      preLoaderRoute: typeof AppOutreachFootprintsEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/footprints': {
      id: '/_app/outreach/footprints'
      path: '/outreach/footprints'
      fullPath: '/outreach/footprints'
      preLoaderRoute: typeof AppOutreachFootprintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/favorites-empty': {
      id: '/_app/outreach/favorites-empty'
      path: '/outreach/favorites-empty'
      fullPath: '/outreach/favorites-empty'
      preLoaderRoute: typeof AppOutreachFavoritesEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/favorites': {
      id: '/_app/outreach/favorites'
      path: '/outreach/favorites'
      fullPath: '/outreach/favorites'
      preLoaderRoute: typeof AppOutreachFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise': {
      id: '/_app/outreach/enterprise'
      path: '/outreach/enterprise'
      fullPath: '/outreach/enterprise'
      preLoaderRoute: typeof AppOutreachEnterpriseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/conversations': {
      id: '/_app/outreach/conversations'
      path: '/outreach/conversations'
      fullPath: '/outreach/conversations'
      preLoaderRoute: typeof AppOutreachConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/bills': {
      id: '/_app/outreach/bills'
      path: '/outreach/bills'
      fullPath: '/outreach/bills'
      preLoaderRoute: typeof AppOutreachBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/billing-empty': {
      id: '/_app/outreach/billing-empty'
      path: '/outreach/billing-empty'
      fullPath: '/outreach/billing-empty'
      preLoaderRoute: typeof AppOutreachBillingEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/billing': {
      id: '/_app/outreach/billing'
      path: '/outreach/billing'
      fullPath: '/outreach/billing'
      preLoaderRoute: typeof AppOutreachBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/products/': {
      id: '/_app/outreach/products/'
      path: '/outreach/products'
      fullPath: '/outreach/products/'
      preLoaderRoute: typeof AppOutreachProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise/': {
      id: '/_app/outreach/enterprise/'
      path: '/'
      fullPath: '/outreach/enterprise/'
      preLoaderRoute: typeof AppOutreachEnterpriseIndexRouteImport
      parentRoute: typeof AppOutreachEnterpriseRoute
    }
    '/_app/outreach/social/reach': {
      id: '/_app/outreach/social/reach'
      path: '/outreach/social/reach'
      fullPath: '/outreach/social/reach'
      preLoaderRoute: typeof AppOutreachSocialReachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/social/friends': {
      id: '/_app/outreach/social/friends'
      path: '/outreach/social/friends'
      fullPath: '/outreach/social/friends'
      preLoaderRoute: typeof AppOutreachSocialFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/social/dm': {
      id: '/_app/outreach/social/dm'
      path: '/outreach/social/dm'
      fullPath: '/outreach/social/dm'
      preLoaderRoute: typeof AppOutreachSocialDmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/social/accounts': {
      id: '/_app/outreach/social/accounts'
      path: '/outreach/social/accounts'
      fullPath: '/outreach/social/accounts'
      preLoaderRoute: typeof AppOutreachSocialAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/products/$hs': {
      id: '/_app/outreach/products/$hs'
      path: '/outreach/products/$hs'
      fullPath: '/outreach/products/$hs'
      preLoaderRoute: typeof AppOutreachProductsHsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise/$id': {
      id: '/_app/outreach/enterprise/$id'
      path: '/$id'
      fullPath: '/outreach/enterprise/$id'
      preLoaderRoute: typeof AppOutreachEnterpriseIdRouteImport
      parentRoute: typeof AppOutreachEnterpriseRoute
    }
    '/_app/outreach/admin/sms-templates': {
      id: '/_app/outreach/admin/sms-templates'
      path: '/outreach/admin/sms-templates'
      fullPath: '/outreach/admin/sms-templates'
      preLoaderRoute: typeof AppOutreachAdminSmsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/admin/sms-routing': {
      id: '/_app/outreach/admin/sms-routing'
      path: '/outreach/admin/sms-routing'
      fullPath: '/outreach/admin/sms-routing'
      preLoaderRoute: typeof AppOutreachAdminSmsRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/admin/sms-providers': {
      id: '/_app/outreach/admin/sms-providers'
      path: '/outreach/admin/sms-providers'
      fullPath: '/outreach/admin/sms-providers'
      preLoaderRoute: typeof AppOutreachAdminSmsProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/admin/invoice-review': {
      id: '/_app/outreach/admin/invoice-review'
      path: '/outreach/admin/invoice-review'
      fullPath: '/outreach/admin/invoice-review'
      preLoaderRoute: typeof AppOutreachAdminInvoiceReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/admin/email-providers': {
      id: '/_app/outreach/admin/email-providers'
      path: '/outreach/admin/email-providers'
      fullPath: '/outreach/admin/email-providers'
      preLoaderRoute: typeof AppOutreachAdminEmailProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/admin/email-accounts': {
      id: '/_app/outreach/admin/email-accounts'
      path: '/outreach/admin/email-accounts'
      fullPath: '/outreach/admin/email-accounts'
      preLoaderRoute: typeof AppOutreachAdminEmailAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/social/reach/': {
      id: '/_app/outreach/social/reach/'
      path: '/'
      fullPath: '/outreach/social/reach/'
      preLoaderRoute: typeof AppOutreachSocialReachIndexRouteImport
      parentRoute: typeof AppOutreachSocialReachRoute
    }
    '/_app/outreach/social/prospecting/': {
      id: '/_app/outreach/social/prospecting/'
      path: '/outreach/social/prospecting'
      fullPath: '/outreach/social/prospecting/'
      preLoaderRoute: typeof AppOutreachSocialProspectingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise/$id/': {
      id: '/_app/outreach/enterprise/$id/'
      path: '/'
      fullPath: '/outreach/enterprise/$id/'
      preLoaderRoute: typeof AppOutreachEnterpriseIdIndexRouteImport
      parentRoute: typeof AppOutreachEnterpriseIdRoute
    }
    '/_app/outreach/social/reach/dm': {
      id: '/_app/outreach/social/reach/dm'
      path: '/dm'
      fullPath: '/outreach/social/reach/dm'
      preLoaderRoute: typeof AppOutreachSocialReachDmRouteImport
      parentRoute: typeof AppOutreachSocialReachRoute
    }
    '/_app/outreach/social/prospecting/$taskId': {
      id: '/_app/outreach/social/prospecting/$taskId'
      path: '/outreach/social/prospecting/$taskId'
      fullPath: '/outreach/social/prospecting/$taskId'
      preLoaderRoute: typeof AppOutreachSocialProspectingTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/social/reach/prospecting/': {
      id: '/_app/outreach/social/reach/prospecting/'
      path: '/prospecting'
      fullPath: '/outreach/social/reach/prospecting/'
      preLoaderRoute: typeof AppOutreachSocialReachProspectingIndexRouteImport
      parentRoute: typeof AppOutreachSocialReachRoute
    }
    '/_app/outreach/social/reach/prospecting/$taskId': {
      id: '/_app/outreach/social/reach/prospecting/$taskId'
      path: '/prospecting/$taskId'
      fullPath: '/outreach/social/reach/prospecting/$taskId'
      preLoaderRoute: typeof AppOutreachSocialReachProspectingTaskIdRouteImport
      parentRoute: typeof AppOutreachSocialReachRoute
    }
    '/_app/outreach/enterprise/$id/contact/$idx': {
      id: '/_app/outreach/enterprise/$id/contact/$idx'
      path: '/contact/$idx'
      fullPath: '/outreach/enterprise/$id/contact/$idx'
      preLoaderRoute: typeof AppOutreachEnterpriseIdContactIdxRouteImport
      parentRoute: typeof AppOutreachEnterpriseIdRoute
    }
  }
}

interface AppOutreachEnterpriseIdRouteChildren {
  AppOutreachEnterpriseIdIndexRoute: typeof AppOutreachEnterpriseIdIndexRoute
  AppOutreachEnterpriseIdContactIdxRoute: typeof AppOutreachEnterpriseIdContactIdxRoute
}

const AppOutreachEnterpriseIdRouteChildren: AppOutreachEnterpriseIdRouteChildren =
  {
    AppOutreachEnterpriseIdIndexRoute: AppOutreachEnterpriseIdIndexRoute,
    AppOutreachEnterpriseIdContactIdxRoute:
      AppOutreachEnterpriseIdContactIdxRoute,
  }

const AppOutreachEnterpriseIdRouteWithChildren =
  AppOutreachEnterpriseIdRoute._addFileChildren(
    AppOutreachEnterpriseIdRouteChildren,
  )

interface AppOutreachEnterpriseRouteChildren {
  AppOutreachEnterpriseIdRoute: typeof AppOutreachEnterpriseIdRouteWithChildren
  AppOutreachEnterpriseIndexRoute: typeof AppOutreachEnterpriseIndexRoute
}

const AppOutreachEnterpriseRouteChildren: AppOutreachEnterpriseRouteChildren = {
  AppOutreachEnterpriseIdRoute: AppOutreachEnterpriseIdRouteWithChildren,
  AppOutreachEnterpriseIndexRoute: AppOutreachEnterpriseIndexRoute,
}

const AppOutreachEnterpriseRouteWithChildren =
  AppOutreachEnterpriseRoute._addFileChildren(
    AppOutreachEnterpriseRouteChildren,
  )

interface AppOutreachSocialReachRouteChildren {
  AppOutreachSocialReachDmRoute: typeof AppOutreachSocialReachDmRoute
  AppOutreachSocialReachIndexRoute: typeof AppOutreachSocialReachIndexRoute
  AppOutreachSocialReachProspectingTaskIdRoute: typeof AppOutreachSocialReachProspectingTaskIdRoute
  AppOutreachSocialReachProspectingIndexRoute: typeof AppOutreachSocialReachProspectingIndexRoute
}

const AppOutreachSocialReachRouteChildren: AppOutreachSocialReachRouteChildren =
  {
    AppOutreachSocialReachDmRoute: AppOutreachSocialReachDmRoute,
    AppOutreachSocialReachIndexRoute: AppOutreachSocialReachIndexRoute,
    AppOutreachSocialReachProspectingTaskIdRoute:
      AppOutreachSocialReachProspectingTaskIdRoute,
    AppOutreachSocialReachProspectingIndexRoute:
      AppOutreachSocialReachProspectingIndexRoute,
  }

const AppOutreachSocialReachRouteWithChildren =
  AppOutreachSocialReachRoute._addFileChildren(
    AppOutreachSocialReachRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOutreachBillingRoute: typeof AppOutreachBillingRoute
  AppOutreachBillingEmptyRoute: typeof AppOutreachBillingEmptyRoute
  AppOutreachBillsRoute: typeof AppOutreachBillsRoute
  AppOutreachConversationsRoute: typeof AppOutreachConversationsRoute
  AppOutreachEnterpriseRoute: typeof AppOutreachEnterpriseRouteWithChildren
  AppOutreachFavoritesRoute: typeof AppOutreachFavoritesRoute
  AppOutreachFavoritesEmptyRoute: typeof AppOutreachFavoritesEmptyRoute
  AppOutreachFootprintsRoute: typeof AppOutreachFootprintsRoute
  AppOutreachFootprintsEmptyRoute: typeof AppOutreachFootprintsEmptyRoute
  AppOutreachInquiryDispatchRoute: typeof AppOutreachInquiryDispatchRoute
  AppOutreachInvoicesRoute: typeof AppOutreachInvoicesRoute
  AppOutreachLeadsRoute: typeof AppOutreachLeadsRoute
  AppOutreachMailboxesRoute: typeof AppOutreachMailboxesRoute
  AppOutreachMyProfileRoute: typeof AppOutreachMyProfileRoute
  AppOutreachReachRoute: typeof AppOutreachReachRoute
  AppOutreachReachEmptyRoute: typeof AppOutreachReachEmptyRoute
  AppOutreachRechargeRoute: typeof AppOutreachRechargeRoute
  AppOutreachSearchRoute: typeof AppOutreachSearchRoute
  AppOutreachSuppressionsRoute: typeof AppOutreachSuppressionsRoute
  AppOutreachUnlockedRoute: typeof AppOutreachUnlockedRoute
  AppOutreachUsersRoute: typeof AppOutreachUsersRoute
  AppOutreachIndexRoute: typeof AppOutreachIndexRoute
  AppOutreachAdminEmailAccountsRoute: typeof AppOutreachAdminEmailAccountsRoute
  AppOutreachAdminEmailProvidersRoute: typeof AppOutreachAdminEmailProvidersRoute
  AppOutreachAdminInvoiceReviewRoute: typeof AppOutreachAdminInvoiceReviewRoute
  AppOutreachAdminSmsProvidersRoute: typeof AppOutreachAdminSmsProvidersRoute
  AppOutreachAdminSmsRoutingRoute: typeof AppOutreachAdminSmsRoutingRoute
  AppOutreachAdminSmsTemplatesRoute: typeof AppOutreachAdminSmsTemplatesRoute
  AppOutreachProductsHsRoute: typeof AppOutreachProductsHsRoute
  AppOutreachSocialAccountsRoute: typeof AppOutreachSocialAccountsRoute
  AppOutreachSocialDmRoute: typeof AppOutreachSocialDmRoute
  AppOutreachSocialFriendsRoute: typeof AppOutreachSocialFriendsRoute
  AppOutreachSocialReachRoute: typeof AppOutreachSocialReachRouteWithChildren
  AppOutreachProductsIndexRoute: typeof AppOutreachProductsIndexRoute
  AppOutreachSocialProspectingTaskIdRoute: typeof AppOutreachSocialProspectingTaskIdRoute
  AppOutreachSocialProspectingIndexRoute: typeof AppOutreachSocialProspectingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOutreachBillingRoute: AppOutreachBillingRoute,
  AppOutreachBillingEmptyRoute: AppOutreachBillingEmptyRoute,
  AppOutreachBillsRoute: AppOutreachBillsRoute,
  AppOutreachConversationsRoute: AppOutreachConversationsRoute,
  AppOutreachEnterpriseRoute: AppOutreachEnterpriseRouteWithChildren,
  AppOutreachFavoritesRoute: AppOutreachFavoritesRoute,
  AppOutreachFavoritesEmptyRoute: AppOutreachFavoritesEmptyRoute,
  AppOutreachFootprintsRoute: AppOutreachFootprintsRoute,
  AppOutreachFootprintsEmptyRoute: AppOutreachFootprintsEmptyRoute,
  AppOutreachInquiryDispatchRoute: AppOutreachInquiryDispatchRoute,
  AppOutreachInvoicesRoute: AppOutreachInvoicesRoute,
  AppOutreachLeadsRoute: AppOutreachLeadsRoute,
  AppOutreachMailboxesRoute: AppOutreachMailboxesRoute,
  AppOutreachMyProfileRoute: AppOutreachMyProfileRoute,
  AppOutreachReachRoute: AppOutreachReachRoute,
  AppOutreachReachEmptyRoute: AppOutreachReachEmptyRoute,
  AppOutreachRechargeRoute: AppOutreachRechargeRoute,
  AppOutreachSearchRoute: AppOutreachSearchRoute,
  AppOutreachSuppressionsRoute: AppOutreachSuppressionsRoute,
  AppOutreachUnlockedRoute: AppOutreachUnlockedRoute,
  AppOutreachUsersRoute: AppOutreachUsersRoute,
  AppOutreachIndexRoute: AppOutreachIndexRoute,
  AppOutreachAdminEmailAccountsRoute: AppOutreachAdminEmailAccountsRoute,
  AppOutreachAdminEmailProvidersRoute: AppOutreachAdminEmailProvidersRoute,
  AppOutreachAdminInvoiceReviewRoute: AppOutreachAdminInvoiceReviewRoute,
  AppOutreachAdminSmsProvidersRoute: AppOutreachAdminSmsProvidersRoute,
  AppOutreachAdminSmsRoutingRoute: AppOutreachAdminSmsRoutingRoute,
  AppOutreachAdminSmsTemplatesRoute: AppOutreachAdminSmsTemplatesRoute,
  AppOutreachProductsHsRoute: AppOutreachProductsHsRoute,
  AppOutreachSocialAccountsRoute: AppOutreachSocialAccountsRoute,
  AppOutreachSocialDmRoute: AppOutreachSocialDmRoute,
  AppOutreachSocialFriendsRoute: AppOutreachSocialFriendsRoute,
  AppOutreachSocialReachRoute: AppOutreachSocialReachRouteWithChildren,
  AppOutreachProductsIndexRoute: AppOutreachProductsIndexRoute,
  AppOutreachSocialProspectingTaskIdRoute:
    AppOutreachSocialProspectingTaskIdRoute,
  AppOutreachSocialProspectingIndexRoute:
    AppOutreachSocialProspectingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
